FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .
RUN npx prisma generate
RUN npm run build

RUN mkdir -p uploads

EXPOSE 3001

CMD ["npm", "start"]
